const lessonData = {};

lessonData["01_Aprilia.mp3"] = [{
    text: "Aprilia started after World War II in Italy, making bicycles and then small scooters. However, it quickly became a legend in the world of racing. Aprilia is famous for winning almost 300 world championship races. They focus on making 'sportbikes' that are very light and very fast. Their most famous modern bike is the RSV4, which is built for the race track but can be driven on the road. Aprilia is a brand for people who love speed and Italian engineering. They use a lot of high-tech electronics to help the driver stay safe at high speeds. Even though it is a smaller company than some others, Aprilia is respected globally for its incredible success in competition.",
    dict: { "started": "başladı", "bicycles": "bisikletler", "scooters": "scooterlar", "quickly": "hızlıca", "legend": "efsane", "racing": "yarış", "winning": "kazanma", "championship": "şampiyona", "races": "yarışlar", "focus": "odaklanmak", "light": "hafif", "fast": "hızlı", "modern": "modern", "track": "pist", "driven": "sürülen", "road": "yol", "brand": "marka", "speed": "hız", "engineering": "mühendislik", "electronics": "elektronik", "stay": "kalmak", "safe": "güvenli", "smaller": "daha küçük", "respected": "saygı duyulan", "globally": "küresel olarak", "incredible": "inanılmaz", "success": "başarı", "competition": "rekabet" },
    questions: [ {q:"Did Aprilia start after World War II?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they make bicycles first?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they focus on heavy cruisers?", a_en:"No", a_tr:"Hayır"}, {q:"Is the RSV4 built for the race track?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they use high-tech electronics for safety?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Aprilia a huge company compared to others?", a_en:"No", a_tr:"Hayır"}, {q:"Are they respected globally for racing?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_BMWMotorrad.mp3"] = [{
    text: "BMW is famous for cars, but they have been making motorcycles since 1923. Their first bike was the R32, which used a special engine design called a 'Boxer' engine where the cylinders stick out to the sides. This design is still used today! BMW is the king of 'adventure' motorcycles. Their GS series is the most famous adventure bike in the world; it is built for long trips across mountains and deserts. Many people use BMW bikes to travel around the world because they are very tough and comfortable. BMW represents German quality and engineering. They are perfect for riders who want a motorcycle that can go anywhere and last for a very long time.",
    dict: { "famous": "ünlü", "cars": "arabalar", "making": "yapan", "motorcycles": "motosikletler", "first": "ilk", "special": "özel", "engine": "motor", "design": "tasarım", "called": "adlandırılan", "cylinders": "silindirler", "stick out": "dışarı çıkmak", "sides": "yanlar", "today": "bugün", "king": "kral", "adventure": "macera", "series": "seri", "trips": "geziler/yolculuklar", "across": "boyunca", "mountains": "dağlar", "deserts": "çöller", "travel": "seyahat etmek", "around": "etrafında", "world": "dünya", "tough": "sert/dayanıklı", "comfortable": "rahat", "represents": "temsil eder", "quality": "kalite", "perfect": "mükemmel", "riders": "sürücüler", "anywhere": "herhangi bir yer", "last": "sürmek/dayanmak", "long": "uzun" },
    questions: [ {q:"Has BMW made motorcycles since 1923?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their engine design called a Boxer?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the cylinders stick out to the sides?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the GS series built only for city roads?", a_en:"No", a_tr:"Hayır"}, {q:"Are BMW bikes tough and comfortable?", a_en:"Yes", a_tr:"Evet"}, {q:"Does BMW represent Italian engineering?", a_en:"No", a_tr:"Hayır"}, {q:"Can these motorcycles go anywhere?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_BSA.mp3"] = [{
    text: "BSA stands for Birmingham Small Arms. As the name suggests, they originally made guns, but they became the largest motorcycle manufacturer in the world in the 1950s. At one time, one in every four motorcycles on the road was a BSA. They are a classic British brand famous for bikes like the 'Gold Star,' which was one of the fastest motorcycles of its time. BSA bikes were known for being simple, strong, and very stylish. Although the company closed for many years, it has recently returned with new models that look like the old classics. For many people, BSA represents the 'Golden Age' of British motorcycling and a time when Britain ruled the roads.",
    dict: { "stands for": "anlamına gelir", "originally": "başlangıçta", "guns": "silahlar", "largest": "en büyük", "manufacturer": "üretici", "every": "her", "road": "yol", "classic": "klasik", "brand": "marka", "fastest": "en hızlı", "known": "bilinen", "simple": "basit", "strong": "güçlü", "stylish": "şık", "closed": "kapandı", "years": "yıllar", "recently": "son zamanlarda", "returned": "geri döndü", "models": "modeller", "look like": "gibi görünmek", "represents": "temsil eder", "Age": "çağ/dönem", "ruled": "yönetti/hakim oldu" },
    questions: [ {q:"Did BSA originally make guns?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they the largest motorcycle manufacturer in the 1950s?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the 'Gold Star' a very slow motorcycle?", a_en:"No", a_tr:"Hayır"}, {q:"Were BSA bikes known for being strong and stylish?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the company stay open without ever closing?", a_en:"No", a_tr:"Hayır"}, {q:"Have they returned with new models recently?", a_en:"Yes", a_tr:"Evet"}, {q:"Does BSA represent the Golden Age of British motorcycling?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_Ducati.mp3"] = [{
    text: "Ducati is often called the 'Ferrari of motorcycles.' This Italian brand is famous for three things: beautiful red paint, incredible speed, and a unique engine sound. Ducati started by making radio parts but began making engines for bicycles after the war. Today, they make some of the most expensive and high-performance motorcycles in the world. Their 'Panigale' series is a dream bike for many sportbike fans. Ducati uses a special 'Desmodromic' system in their engines that makes them very powerful. When you see a Ducati, you see a masterpiece of Italian design. It is a brand for people who want the ultimate in performance and style, even if it costs a lot of money.",
    dict: { "often": "sık sık", "called": "adlandırılan", "brand": "marka", "paint": "boya", "incredible": "inanılmaz", "speed": "hız", "unique": "benzersiz", "sound": "ses", "parts": "parçalar", "war": "savaş", "expensive": "pahalı", "performance": "performans", "dream": "rüya", "fans": "hayranlar", "special": "özel", "system": "sistem", "powerful": "güçlü", "masterpiece": "şaheser", "design": "tasarım", "ultimate": "en üst düzey", "style": "stil/tarz", "costs": "mal olur", "money": "para" },
    questions: [ {q:"Is Ducati called the Ferrari of motorcycles?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for beautiful red paint?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they start by making car engines?", a_en:"No", a_tr:"Hayır"}, {q:"Do they make very expensive motorcycles?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Panigale series a dream sportbike?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they use a special Desmodromic system?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Ducati motorcycles cheap?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["05_HarleyDavidson.mp3"] = [{
    text: "Harley-Davidson is the most famous motorcycle brand in history. Started in a small shed in Milwaukee, it became a symbol of American freedom. Harley is famous for the 'cruiser' style of motorcycle, where the rider sits low and comfortable. Their engines have a very unique 'potato-potato' sound that everyone recognizes. Harley-Davidson is more than just a bike; it is a lifestyle. Millions of people join 'H.O.G.' (Harley Owners Group) clubs and travel together on long road trips across the USA. While they are not the fastest bikes, they are built for the open road and for people who love the feeling of the wind and the heavy metal of a classic American machine.",
    dict: { "most": "en", "famous": "ünlü", "history": "tarih", "small": "küçük", "shed": "kulübe/baraka", "symbol": "sembol", "freedom": "özgürlük", "style": "stil/tarz", "rider": "sürücü", "sits": "oturur", "low": "alçak", "comfortable": "rahat", "unique": "benzersiz", "sound": "ses", "recognizes": "tanır", "lifestyle": "yaşam tarzı", "join": "katılmak", "clubs": "kulüpler", "travel": "seyahat etmek", "together": "birlikte", "trips": "geziler/yolculuklar", "across": "boyunca", "fastest": "en hızlı", "built": "inşa edilmiş", "open": "açık", "road": "yol", "feeling": "his/duygu", "wind": "rüzgar", "heavy": "ağır", "metal": "metal" },
    questions: [ {q:"Did Harley-Davidson start in a small shed?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it a symbol of American freedom?", a_en:"Yes", a_tr:"Evet"}, {q:"Are their motorcycles built for racing on tracks?", a_en:"No", a_tr:"Hayır"}, {q:"Does the engine make a unique sound?", a_en:"Yes", a_tr:"Evet"}, {q:"Do millions of people join H.O.G. clubs?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Harley-Davidson bikes the fastest in the world?", a_en:"No", a_tr:"Hayır"}, {q:"Are they built for the open road?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_Honda.mp3"] = [{
    text: "Honda is the biggest motorcycle company in the world. It was started by Soichiro Honda, who wanted to make simple and reliable transportation for everyone. Honda’s most famous bike is the 'Super Cub.' It is the best-selling vehicle in history, with over 100 million sold! Honda is famous for its slogan, 'You meet the nicest people on a Honda,' which changed how people viewed motorcyclists. Honda makes everything from tiny scooters to the massive 'Gold Wing' touring bike and the fast 'CBR' sportbikes. They are known for being incredibly reliable—a Honda engine almost never breaks. If you want a smart, reliable, and high-quality bike, Honda is usually the first choice.",
    dict: { "biggest": "en büyük", "company": "şirket", "started": "başlatıldı", "wanted": "istedi", "simple": "basit", "reliable": "güvenilir", "transportation": "ulaşım", "everyone": "herkes", "best-selling": "en çok satan", "vehicle": "araç", "history": "tarih", "sold": "satıldı", "slogan": "slogan", "nicest": "en iyi/en nazik", "changed": "değiştirdi", "viewed": "gördü/bakış açısı", "makes": "yapar/üretir", "everything": "her şey", "tiny": "minik", "scooters": "scooterlar", "massive": "muazzam", "touring": "tur (motosikleti)", "fast": "hızlı", "incredibly": "inanılmaz derecede", "almost": "neredeyse", "never": "asla", "breaks": "bozulur/kırılır", "smart": "akıllı", "high-quality": "yüksek kaliteli", "choice": "seçim" },
    questions: [ {q:"Is Honda the biggest motorcycle company in the world?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Soichiro Honda want to make reliable transportation?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Super Cub the best-selling vehicle in history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their slogan change how people viewed motorcyclists?", a_en:"Yes", a_tr:"Evet"}, {q:"Do Honda engines break very often?", a_en:"No", a_tr:"Hayır"}, {q:"Do they make massive touring bikes like the Gold Wing?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Honda usually a smart and reliable choice?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_Husqvarna.mp3"] = [{
    text: "Husqvarna is a Swedish brand that is one of the oldest in the world. They started by making guns and sewing machines, but they became legends in off-road racing. If you love 'dirt bikes' or motocross, you know Husqvarna. They won many world titles in the 1960s and 70s. Recently, the brand has become very popular for street bikes too. Their 'Svartpilen' and 'Vitpilen' models have a very unique, modern 'Scandi' design that looks like nothing else on the road. Husqvarna is a brand for people who like to be different and want a bike that is very light, agile, and has a great history of winning in the mud and dirt.",
    dict: { "Swedish": "İsveç", "brand": "marka", "oldest": "en eski", "started": "başladı", "guns": "silahlar", "sewing": "dikiş", "machines": "makineler", "legends": "efsaneler", "racing": "yarış", "dirt": "kir/toprak", "won": "kazandı", "titles": "unvanlar/şampiyonluklar", "recently": "son zamanlarda", "popular": "popüler", "street": "sokak", "models": "modeller", "unique": "benzersiz", "modern": "modern", "design": "tasarım", "nothing": "hiçbir şey", "else": "başka", "different": "farklı", "light": "hafif", "agile": "çevik", "history": "tarih", "winning": "kazanma", "mud": "çamur" },
    questions: [ {q:"Is Husqvarna one of the oldest brands in the world?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they start by making only motorcycles?", a_en:"No", a_tr:"Hayır"}, {q:"Did they become legends in off-road racing?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have a modern 'Scandi' design?", a_en:"Yes", a_tr:"Evet"}, {q:"Does their design look like nothing else on the road?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Husqvarna bikes very heavy?", a_en:"No", a_tr:"Hayır"}, {q:"Do they have a history of winning in the mud?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_IndianMotorcycle.mp3"] = [{
    text: "Indian is actually the oldest American motorcycle company, started two years before Harley-Davidson. In the early 1900s, it was the largest manufacturer in the world. Indian is famous for the 'Chief' and the 'Scout' models, which had beautiful, classic designs with large fenders. A man named Burt Munro famously used an old Indian Scout to set a world speed record in the 1960s. After being closed for many years, the brand was brought back to life and now makes high-quality cruisers that compete with Harley-Davidson. Indian represents the original spirit of American motorcycling and is loved by riders who appreciate history and beautiful, classic lines.",
    dict: { "actually": "aslında", "oldest": "en eski", "company": "şirket", "started": "başlatıldı", "before": "önce", "early": "erken", "largest": "en büyük", "manufacturer": "üretici", "famous": "ünlü", "models": "modeller", "beautiful": "güzel", "classic": "klasik", "designs": "tasarımlar", "large": "büyük", "fenders": "çamurluklar", "named": "adında", "used": "kullandı", "old": "eski", "record": "rekor", "closed": "kapalı", "brought back": "geri getirildi", "life": "hayat", "makes": "yapar", "compete": "rekabet etmek", "represents": "temsil eder", "original": "orijinal", "spirit": "ruh", "loved": "sevilir", "appreciate": "takdir etmek" },
    questions: [ {q:"Is Indian the oldest American motorcycle company?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it start after Harley-Davidson?", a_en:"No", a_tr:"Hayır"}, {q:"Are the 'Chief' and 'Scout' famous models?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Burt Munro set a speed record on an Indian Scout?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the company stay open forever without closing?", a_en:"No", a_tr:"Hayır"}, {q:"Does the brand now compete with Harley-Davidson?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Indian represent the original spirit of American motorcycling?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_Kawasaki.mp3"] = [{
    text: "Kawasaki is known as the 'rebel' of the Japanese brands. Their motorcycles are almost always bright lime-green. Kawasaki is famous for power and speed. Their 'Ninja' series of sportbikes is one of the most famous names in the world. In the 1970s, their Z1 model was the fastest bike you could buy. Today, they make the H2, which uses a 'supercharger' to go incredibly fast—it is one of the most powerful production bikes ever made. Kawasaki is a brand for people who love adrenaline and want a motorcycle that feels aggressive and strong. They are built for the street and the track, and they always focus on being the fastest.",
    dict: { "known": "bilinen", "rebel": "asi", "brands": "markalar", "almost": "neredeyse", "always": "her zaman", "bright": "parlak", "green": "yeşil", "famous": "ünlü", "power": "güç", "speed": "hız", "series": "seri", "names": "isimler", "world": "dünya", "fastest": "en hızlı", "buy": "satın almak", "today": "bugün", "make": "yaparlar", "uses": "kullanır", "incredibly": "inanılmaz derecede", "powerful": "güçlü", "production": "üretim", "ever": "şimdiye kadar", "made": "yapılmış", "love": "sever", "adrenaline": "adrenalin", "feels": "hissettirir", "aggressive": "agresif", "strong": "güçlü", "built": "inşa edilmiş", "street": "sokak", "track": "pist", "focus": "odaklanmak" },
    questions: [ {q:"Is Kawasaki known as the rebel of the Japanese brands?", a_en:"Yes", a_tr:"Evet"}, {q:"Are their motorcycles usually painted red?", a_en:"No", a_tr:"Hayır"}, {q:"Is the 'Ninja' series very famous?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Z1 model the fastest bike in the 1970s?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the H2 model use a supercharger?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Kawasaki a brand for people who want a slow ride?", a_en:"No", a_tr:"Hayır"}, {q:"Do they focus on being the fastest?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_KTM.mp3"] = [{
    text: "KTM is an Austrian brand that is famous for its bright orange color and its slogan, 'Ready to Race.' For a long time, KTM was the king of off-road and 'Enduro' racing. If you watch a race in the desert or on a mountain, you will see many orange KTM bikes. Recently, they have also become very successful in MotoGP racing and street bikes. Their 'Duke' series is famous for being very light and easy to 'flick' around corners. KTM bikes are designed to be aggressive and high-performance. They are perfect for riders who want a bike that feels like a racing machine, whether they are on the dirt or on the road.",
    dict: { "Austrian": "Avusturyalı", "brand": "marka", "famous": "ünlü", "bright": "parlak", "orange": "turuncu", "color": "renk", "slogan": "slogan", "ready": "hazır", "race": "yarış", "king": "kral", "racing": "yarış", "watch": "izlemek", "desert": "çöl", "mountain": "dağ", "see": "görmek", "many": "birçok", "bikes": "motosikletler", "recently": "son zamanlarda", "also": "ayrıca", "become": "oldu", "successful": "başarılı", "street": "sokak", "series": "seri", "light": "hafif", "easy": "kolay", "flick": "hızlıca yönlendirmek", "around": "etrafında", "corners": "virajlar", "designed": "tasarlanmış", "aggressive": "agresif", "performance": "performans", "perfect": "mükemmel", "riders": "sürücüler", "feels": "hissettirir", "machine": "makine", "whether": "ister ... ister", "dirt": "kir/toprak", "road": "yol" },
    questions: [ {q:"Is KTM famous for its bright orange color?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their slogan 'Ready to Relax'?", a_en:"No", a_tr:"Hayır"}, {q:"Was KTM the king of off-road racing?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they successful in MotoGP racing now?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the 'Duke' series very heavy?", a_en:"No", a_tr:"Hayır"}, {q:"Are KTM bikes designed to be aggressive?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they feel like racing machines on the road?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_MotoGuzzi.mp3"] = [{
    text: "Moto Guzzi is the oldest European motorcycle manufacturer in continuous production. Based on the shores of Lake Como in Italy, this brand is famous for its very unique engine design. The cylinders stick out to the sides in a 'V' shape, which gives the bike a very cool look and a special feeling when you rev the engine. Moto Guzzi bikes are built for style and long-distance comfort. Their 'V7' model is a classic retro bike that many people love for its simple beauty. Moto Guzzi is a brand for people who appreciate Italian history and want a motorcycle that feels traditional, solid, and very different from the modern Japanese bikes.",
    dict: { "oldest": "en eski", "European": "Avrupalı", "manufacturer": "üretici", "continuous": "sürekli", "production": "üretim", "shores": "kıyılar", "lake": "göl", "brand": "marka", "famous": "ünlü", "unique": "benzersiz", "engine": "motor", "design": "tasarım", "cylinders": "silindirler", "stick out": "dışarı çıkmak", "sides": "yanlar", "shape": "şekil", "gives": "verir", "cool": "havalı", "look": "görünüm", "special": "özel", "feeling": "his/duygu", "rev": "gaz vermek", "built": "inşa edilmiş", "style": "stil/tarz", "long-distance": "uzun mesafe", "comfort": "rahatlık", "classic": "klasik", "love": "sever", "simple": "basit", "beauty": "güzellik", "appreciate": "takdir etmek", "history": "tarih", "traditional": "geleneksel", "solid": "sağlam", "different": "farklı", "modern": "modern" },
    questions: [ {q:"Is Moto Guzzi the oldest European manufacturer in continuous production?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they based in Italy?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the cylinders stick out in a 'V' shape?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they built only for racing speeds?", a_en:"No", a_tr:"Hayır"}, {q:"Is the 'V7' model a classic retro bike?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the brand appeal to people who like traditional bikes?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they feel exactly like modern Japanese bikes?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["12_MVAgusta.mp3"] = [{
    text: "MV Agusta is often called 'Motorcycle Art.' This Italian brand is famous for making some of the most beautiful and exclusive motorcycles in history. They became legends by winning 270 Grand Prix races with the famous rider Giacomo Agostini. MV Agusta bikes are very expensive and are built with incredible attention to detail. Models like the 'F4' and the 'Brutale' are known for their spectacular designs and screaming four-cylinder engines. They do not make many bikes, so seeing one on the street is very rare. It is a brand for the true connoisseur who wants a motorcycle that is as beautiful to look at as it is fast to drive.",
    dict: { "often": "sık sık", "called": "adlandırılan", "Art": "Sanat", "brand": "marka", "famous": "ünlü", "making": "yapma", "beautiful": "güzel", "exclusive": "özel/seçkin", "history": "tarih", "legends": "efsaneler", "winning": "kazanarak", "races": "yarışlar", "rider": "sürücü", "expensive": "pahalı", "built": "inşa edilmiş", "incredible": "inanılmaz", "attention": "dikkat", "detail": "detay", "Models": "Modeller", "known": "bilinen", "spectacular": "muhteşem", "designs": "tasarımlar", "screaming": "çığlık atan", "engines": "motorlar", "street": "sokak", "rare": "nadir", "true": "gerçek", "connoisseur": "uzman/ehil", "look at": "bakmak", "fast": "hızlı", "drive": "sürmek" },
    questions: [ {q:"Is MV Agusta often called 'Motorcycle Art'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they win 270 Grand Prix races?", a_en:"Yes", a_tr:"Evet"}, {q:"Are MV Agusta bikes very cheap to buy?", a_en:"No", a_tr:"Hayır"}, {q:"Are the 'F4' and 'Brutale' famous models?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make millions of bikes every year?", a_en:"No", a_tr:"Hayır"}, {q:"Is seeing one on the street very rare?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they built with incredible attention to detail?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_Norton.mp3"] = [{
    text: "Norton is one of the most iconic names in British motorcycling history. They became famous at the 'Isle of Man TT,' which is the most dangerous and famous motorcycle race in the world. Norton’s 'Commando' model in the 1960s and 70s was voted 'Machine of the Year' many times. Norton bikes are known for having a very cool, café-racer style and for their excellent handling. The company has had many financial problems over the years, but it is now back with new, high-quality models. Norton represents the spirit of British racing and the 'cool' era of the 1960s when riders would race from one café to another in London.",
    dict: { "iconic": "ikonik/simgeleşmiş", "names": "isimler", "history": "tarih", "became": "oldu", "famous": "ünlü", "dangerous": "tehlikeli", "race": "yarış", "world": "dünya", "model": "model", "voted": "seçildi/oylandı", "Machine": "Makine", "Year": "Yıl", "many": "birçok", "times": "kez/zamanlar", "known": "bilinir", "cool": "havalı", "style": "stil", "excellent": "mükemmel", "handling": "yol tutuşu", "company": "şirket", "financial": "finansal", "problems": "sorunlar", "over": "üzerinden/boyunca", "years": "yıllar", "back": "geri", "new": "yeni", "high-quality": "yüksek kaliteli", "represents": "temsil eder", "spirit": "ruh", "racing": "yarış", "era": "dönem", "riders": "sürücüler", "another": "başka" },
    questions: [ {q:"Is Norton an iconic British brand?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they become famous at the Isle of Man TT?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Commando voted 'Machine of the Year'?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Norton bikes known for bad handling?", a_en:"No", a_tr:"Hayır"}, {q:"Did the company have financial problems in the past?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they represent the 'cool' era of the 1960s?", a_en:"Yes", a_tr:"Evet"}, {q:"Would riders race between cafes in London?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_RoyalEnfield.mp3"] = [{
    text: "Royal Enfield is a brand with a very interesting history. It started in England but is now based in India. Their most famous model is the 'Bullet,' which has been in production since 1932—this is the longest-running motorcycle design in history! Royal Enfield bikes are famous for their classic 'retro' look and their simple, old-fashioned feeling. They are not very fast, but they are very easy to drive and have a great 'thumping' sound. In India, they are a symbol of status and adventure. Today, they are popular all over the world because they are affordable and look like the bikes from the 1950s. They are perfect for people who want a classic-looking motorcycle for a relaxing ride.",
    dict: { "brand": "marka", "interesting": "ilginç", "history": "tarih", "started": "başladı", "based": "merkezli", "famous": "ünlü", "model": "model", "production": "üretim", "since": "den beri", "longest-running": "en uzun süren", "design": "tasarım", "classic": "klasik", "look": "görünüm", "simple": "basit", "old-fashioned": "eski moda", "feeling": "his", "fast": "hızlı", "easy": "kolay", "drive": "sürmek", "great": "harika", "sound": "ses", "symbol": "sembol", "status": "statü", "adventure": "macera", "Today": "bugün", "popular": "popüler", "world": "dünya", "affordable": "uygun fiyatlı", "perfect": "mükemmel", "people": "insanlar", "relaxing": "rahatlatıcı", "ride": "sürüş" },
    questions: [ {q:"Did Royal Enfield start in England?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the brand now based in India?", a_en:"Yes", a_tr:"Evet"}, {q:"Has the Bullet been in production since 1932?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Royal Enfield bikes extremely fast?", a_en:"No", a_tr:"Hayır"}, {q:"Do they have a classic retro look?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they popular because they are very expensive?", a_en:"No", a_tr:"Hayır"}, {q:"Are they perfect for a relaxing ride?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_Suzuki.mp3"] = [{
    text: "Suzuki is a Japanese brand that is known for making very fast and practical motorcycles. They became world-famous in the 1980s and 90s with their 'GSX-R' sportbikes, which were very light and changed how racing bikes were built. Suzuki is also the maker of the 'Hayabusa.' When it was released, the Hayabusa was the fastest production motorcycle in the world, reaching over 300 km/h. Suzuki also makes excellent 'adventure' bikes like the V-Strom and great small bikes for beginners. They are known for providing a lot of performance for a good price. Suzuki is a brand for riders who want a reliable, high-speed machine that is built with great Japanese technology.",
    dict: { "brand": "marka", "known": "bilinen", "making": "yapan", "fast": "hızlı", "practical": "pratik", "motorcycles": "motosikletler", "world-famous": "dünyaca ünlü", "light": "hafif", "changed": "değiştirdi", "racing": "yarış", "built": "inşa edilmiş", "maker": "üretici", "released": "piyasaya sürüldü", "fastest": "en hızlı", "production": "üretim", "world": "dünya", "reaching": "ulaşan", "excellent": "mükemmel", "adventure": "macera", "small": "küçük", "beginners": "yeni başlayanlar", "providing": "sağlayan", "lot": "çok", "performance": "performans", "good": "iyi", "price": "fiyat", "riders": "sürücüler", "reliable": "güvenilir", "high-speed": "yüksek hızlı", "machine": "makine", "technology": "teknoloji" },
    questions: [ {q:"Is Suzuki known for making practical motorcycles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the GSX-R change how racing bikes were built?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Hayabusa a very slow motorcycle?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Hayabusa reach over 300 km/h?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make great small bikes for beginners?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they provide good performance for a low price?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Suzuki built with Japanese technology?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_Triumph.mp3"] = [{
    text: "Triumph is the biggest and most famous British motorcycle brand. They are the makers of the 'Bonneville,' which is named after the place in America where motorcycles go to set speed records. Triumph was the favorite brand of movie stars like Steve McQueen and Marlon Brando. In the 1960s, a Triumph was the coolest thing you could own. Today, they make a great mix of 'Modern Classic' bikes that look old but have new technology, and high-performance 'Triple' engine bikes like the Street Triple. Triumph represents British style and class. Their bikes are known for being very well-made and having a perfect balance of power and comfort.",
    dict: { "biggest": "en büyük", "famous": "ünlü", "British": "İngiliz", "brand": "marka", "makers": "üreticiler", "named": "adlandırılan", "place": "yer", "speed": "hız", "records": "rekorlar", "favorite": "favori", "movie": "film", "stars": "yıldızlar", "coolest": "en havalı", "thing": "şey", "own": "sahip olmak", "Today": "bugün", "make": "yaparlar", "great": "harika", "mix": "karışım", "Classic": "Klasik", "look": "görünür", "old": "eski", "new": "yeni", "technology": "teknoloji", "performance": "performans", "engine": "motor", "represents": "temsil eder", "style": "stil/tarz", "class": "sınıf/kalite", "known": "bilinir", "well-made": "iyi yapılmış", "perfect": "mükemmel", "balance": "denge", "power": "güç", "comfort": "rahatlık" },
    questions: [ {q:"Is Triumph a famous British motorcycle brand?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the 'Bonneville' named after a speed record place?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they favorite bikes of movie stars in the past?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they only make old-fashioned bikes today?", a_en:"No", a_tr:"Hayır"}, {q:"Do Modern Classic bikes have new technology inside?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Triumph represent British style and class?", a_en:"Yes", a_tr:"Evet"}, {q:"Do their bikes have a perfect balance of power and comfort?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_Vespa.mp3"] = [{
    text: "Vespa is not just a motorcycle; it is the most famous scooter in the world. Created by Piaggio after the war, the Vespa was designed to be a cheap and stylish way for Italians to move through crowded cities. The design is iconic, with a step-through frame and a front that protects the rider's clothes from mud. The word 'Vespa' means 'wasp' in Italian because of the sound of its engine. Vespa became a symbol of 'The Good Life' (La Dolce Vita) and has appeared in many famous movies. Today, people all over the world drive Vespas because they are easy to park, use very little fuel, and look incredibly cool. It is the ultimate symbol of urban style.",
    dict: { "just": "sadece", "famous": "ünlü", "scooter": "scooter", "world": "dünya", "Created": "yaratıldı", "after": "sonra", "war": "savaş", "designed": "tasarlandı", "cheap": "ucuz", "stylish": "şık", "way": "yol/yöntem", "move": "hareket etmek", "crowded": "kalabalık", "cities": "şehirler", "design": "tasarım", "iconic": "ikonik", "frame": "şasi/gövde", "front": "ön", "protects": "korur", "clothes": "kıyafetler", "mud": "çamur", "word": "kelime", "means": "anlamına gelir", "wasp": "eşekarısı", "sound": "ses", "engine": "motor", "became": "oldu", "symbol": "sembol", "Life": "Hayat", "appeared": "göründü", "movies": "filmler", "Today": "bugün", "people": "insanlar", "drive": "sürerler", "easy": "kolay", "park": "park etmek", "use": "kullanmak", "little": "az", "fuel": "yakıt", "look": "görünmek", "incredibly": "inanılmaz derecede", "cool": "havalı", "ultimate": "en üst düzey", "urban": "kentsel/şehirli", "style": "tarz" },
    questions: [ {q:"Is the Vespa a famous scooter?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it designed to be cheap and stylish?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the front protect the rider's clothes from mud?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the word 'Vespa' mean 'bird' in Italian?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Vespa appear in many famous movies?", a_en:"Yes", a_tr:"Evet"}, {q:"Do Vespas use a lot of fuel?", a_en:"No", a_tr:"Hayır"}, {q:"Are they easy to park in the city?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_Victory.mp3"] = [{
    text: "Victory was a modern American motorcycle company created to compete with Harley-Davidson. They focused on making large 'cruisers' and 'touring' bikes, but with much more modern designs and engines. Victory bikes were known for being very reliable and for having a very 'smooth' ride compared to the older American brands. They had a very bold, futuristic look that many younger riders liked. Although the company was closed in 2017 by its owner (Polaris) to focus on the Indian brand, Victory is still remembered for bringing new ideas to the American motorcycle market. Many people still own and love their Victory bikes because they are great for long-distance highway traveling.",
    dict: { "modern": "modern", "company": "şirket", "created": "yaratıldı", "compete": "rekabet etmek", "focused": "odaklandı", "making": "yapma", "large": "büyük", "cruisers": "kruvazör motosikletler", "touring": "tur", "bikes": "motosikletler", "designs": "tasarımlar", "engines": "motorlar", "known": "bilinen", "reliable": "güvenilir", "having": "sahip olma", "smooth": "pürüzsüz/yumuşak", "ride": "sürüş", "compared": "kıyasla", "older": "daha eski", "brands": "markalar", "bold": "cesur", "futuristic": "fütüristik/gelecekçi", "look": "görünüm", "younger": "daha genç", "riders": "sürücüler", "liked": "beğendi", "closed": "kapatıldı", "owner": "sahip", "focus": "odaklanmak", "remembered": "hatırlanır", "bringing": "getirmek", "new": "yeni", "ideas": "fikirler", "market": "piyasa", "people": "insanlar", "own": "sahip olmak", "love": "sevmek", "great": "harika", "long-distance": "uzun mesafe", "highway": "otoyol", "traveling": "seyahat" },
    questions: [ {q:"Was Victory created to compete with Harley-Davidson?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they focus on making small scooters?", a_en:"No", a_tr:"Hayır"}, {q:"Were Victory bikes known for a smooth ride?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have a futuristic look?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the company still producing new bikes today?", a_en:"No", a_tr:"Hayır"}, {q:"Did the owner close it to focus on the Indian brand?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they great for long-distance highway traveling?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_Vincent.mp3"] = [{
    text: "Vincent is a legendary British brand that made what was once the 'fastest motorcycle in the world.' Their most famous model, the 'Black Shadow,' could go 125 mph (200 km/h) in 1948! This was incredible for that time. Vincent motorcycles were very expensive and were built with the best engineering available. They were famous for their large, black V-twin engines and their very high quality. There is a very famous photo of a man in his swimming trunks riding a Vincent at high speed to set a record. Even though the company stopped making bikes in 1955, Vincent motorcycles are now worth a lot of money and are considered the 'holy grail' for collectors.",
    dict: { "legendary": "efanevi", "brand": "marka", "made": "yaptı", "once": "bir zamanlar", "fastest": "en hızlı", "world": "dünya", "famous": "ünlü", "model": "model", "could": "yapabildi", "go": "gitmek", "incredible": "inanılmaz", "time": "zaman", "expensive": "pahalı", "built": "inşa edilmiş", "best": "en iyi", "engineering": "mühendislik", "available": "mevcut", "large": "büyük", "black": "siyah", "engines": "motorlar", "high": "yüksek", "quality": "kalite", "photo": "fotoğraf", "man": "adam", "swimming trunks": "mayo", "riding": "süren", "speed": "hız", "record": "rekor", "stopped": "durdurdu", "making": "yapmayı", "bikes": "motosikletler", "now": "şimdi", "worth": "değerinde", "money": "para", "considered": "kabul edilir", "holy grail": "kutsal kase (en değerli şey)", "collectors": "koleksiyoncular" },
    questions: [ {q:"Did Vincent make the fastest motorcycle in the world?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the Black Shadow go 200 km/h in 1948?", a_en:"Yes", a_tr:"Evet"}, {q:"Were Vincent motorcycles very cheap?", a_en:"No", a_tr:"Hayır"}, {q:"Did they use large, black V-twin engines?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the company stop making bikes in 1955?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Vincent motorcycles worth a lot of money today?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they considered the holy grail for collectors?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_Yamaha.mp3"] = [{
    text: "Yamaha is a unique company because they started by making musical instruments like pianos (which is why their logo has three tuning forks). When they started making motorcycles, they used their knowledge of engineering to create high-performance machines. Yamaha is famous for its 'R1' sportbike and its success in racing with the legend Valentino Rossi. They are also known for their 'MT' series, which are very fun street bikes. Yamaha bikes are known for being very exciting to drive and for having excellent handling. They are also leaders in technology, making everything from scooters to off-road bikes and high-speed racing machines. Yamaha is a brand for people who love the 'music' of a great engine.",
    dict: { "unique": "benzersiz", "company": "şirket", "started": "başladı", "making": "yaparak", "musical": "müzikal", "instruments": "enstrümanlar", "pianos": "piyanolar", "logo": "logo", "tuning forks": "akort çatalları", "motorcycles": "motosikletler", "used": "kullandı", "knowledge": "bilgi", "engineering": "mühendislik", "create": "yaratmak", "high-performance": "yüksek performanslı", "machines": "makineler", "famous": "ünlü", "sportbike": "spor motosiklet", "success": "başarı", "racing": "yarış", "legend": "efsane", "also": "ayrıca", "known": "bilinir", "series": "seri", "fun": "eğlenceli", "street": "sokak", "bikes": "motosikletler", "exciting": "heyecan verici", "drive": "sürmek", "excellent": "mükemmel", "handling": "yol tutuşu", "leaders": "liderler", "technology": "teknoloji", "everything": "her şey", "scooters": "scooterlar", "off-road": "arazi", "high-speed": "yüksek hızlı", "brand": "marka", "people": "insanlar", "love": "seven", "music": "müzik", "engine": "motor" },
    questions: [ {q:"Did Yamaha start by making musical instruments?", a_en:"Yes", a_tr:"Evet"}, {q:"Does their logo have three tuning forks?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the 'R1' a famous Yamaha sportbike?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have racing success with Valentino Rossi?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Yamaha bikes boring to drive?", a_en:"No", a_tr:"Hayır"}, {q:"Do they have excellent handling?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make both scooters and off-road bikes?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_ZeroMotorcycles.mp3"] = [{
    text: "Zero Motorcycles is the leader of the electric motorcycle revolution. Based in California, Zero was the first company to make high-performance electric bikes that you could actually buy. Zero bikes have no gearbox or clutch; you just turn the throttle and go! They are incredibly fast because electric motors provide all their power immediately. They are also almost silent, which is a very strange feeling for many traditional riders. Zero is proving that you need no gasoline or loud exhaust to have a spectacular and fun motorcycle. They represent the future of motorcycling and are perfect for people who want high technology and care about the environment.",
    dict: { "leader": "lider", "electric": "elektrikli", "motorcycle": "motosiklet", "revolution": "devrim", "Based": "merkezli", "first": "ilk", "company": "şirket", "make": "yapmak", "high-performance": "yüksek performanslı", "bikes": "motosikletler", "actually": "gerçekten/aslında", "buy": "satın almak", "gearbox": "vites kutusu", "clutch": "debriyaj", "just": "sadece", "turn": "çevirmek", "throttle": "gaz kolu", "go": "gitmek", "incredibly": "inanılmaz derecede", "fast": "hızlı", "motors": "motorlar", "provide": "sağlar", "power": "güç", "immediately": "derhal/anında", "almost": "neredeyse", "silent": "sessiz", "strange": "garip", "feeling": "his", "traditional": "geleneksel", "riders": "sürücüler", "proving": "kanıtlıyor", "gasoline": "benzin", "loud": "gürültülü", "exhaust": "egzoz", "spectacular": "muhteşem", "fun": "eğlenceli", "represent": "temsil eder", "future": "gelecek", "perfect": "mükemmel", "technology": "teknoloji", "care": "önemsemek", "environment": "çevre" },
    questions: [ {q:"Is Zero Motorcycles the leader in electric bikes?", a_en:"Yes", a_tr:"Evet"}, {q:"Do Zero bikes have no gearbox?", a_en:"Yes", a_tr:"Evet"}, {q:"Do you just turn the throttle and go?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they incredibly slow?", a_en:"No", a_tr:"Hayır"}, {q:"Are these motorcycles almost silent?", a_en:"Yes", a_tr:"Evet"}, {q:"Do you need gasoline for a Zero motorcycle?", a_en:"No", a_tr:"Hayır"}, {q:"Are they perfect for people who care about the environment?", a_en:"Yes", a_tr:"Evet"} ]
}];
